-- AlterTable
ALTER TABLE `ServicesCard` ADD COLUMN `annualFees` VARCHAR(191) NULL,
    ADD COLUMN `cardProtectionWith3DSecureText` BOOLEAN NULL,
    ADD COLUMN `creditLimit` VARCHAR(191) NULL,
    ADD COLUMN `fourtyFiveDaysMaximumInterestFree` BOOLEAN NULL,
    ADD COLUMN `freeAnnualFees` VARCHAR(191) NULL,
    ADD COLUMN `freeCashWithdrawal` BOOLEAN NULL,
    ADD COLUMN `freeFlightTickets` BOOLEAN NULL,
    ADD COLUMN `generalConditions` VARCHAR(191) NULL,
    ADD COLUMN `globalPayments` BOOLEAN NULL,
    ADD COLUMN `income` VARCHAR(191) NULL,
    ADD COLUMN `installmentPlanWithInterestOf1Percent` BOOLEAN NULL,
    ADD COLUMN `interestRate` VARCHAR(191) NULL,
    ADD COLUMN `mobiphone` BOOLEAN NULL,
    ADD COLUMN `refund` VARCHAR(191) NULL,
    ADD COLUMN `rewardPoints` BOOLEAN NULL,
    ADD COLUMN `seperateOffer` VARCHAR(191) NULL,
    ADD COLUMN `transactionLimit` VARCHAR(191) NULL,
    ADD COLUMN `upTo50PercentOff` BOOLEAN NULL,
    ADD COLUMN `withdrawMoneyUpTo85Percent` BOOLEAN NULL;
